/* ═══════════════════════════════════════════════════════════
   QuickToolLab — Tools, AI Tools & Pinned Data
   ═══════════════════════════════════════════════════════════ */

/* ── Pinned Recommendations ── */
const PINNED = [
    { icon:'🔍', name:'JSON Crack', brand:'jsoncrack.com', desc:{zh:'JSON 结构可视化，将嵌套数据转为树状图，一眼看清层级',en:'Visualize JSON as an interactive graph',ja:'JSONをグラフで可視化'}, href:'https://jsoncrack.com', cat:'dev' },
    { icon:'⚡', name:'Transform.tools', brand:'transform.tools', desc:{zh:'数十种格式互转：JSON→TS、SQL→Go 等，开发必备',en:'Convert between dozens of formats: JSON to TS, SQL to Go…',ja:'JSON→TSなど多種フォーマット変換'}, href:'https://transform.tools', cat:'dev' },
    { icon:'🔑', name:'JWT Debugger', brand:'jwt.io', desc:{zh:'快速解码 JWT Token，查看 payload、过期时间和签名信息',en:'Decode & verify JWT tokens instantly',ja:'JWTトークンを即座に解析'}, href:'https://jwt.io', cat:'dev' },
    { icon:'◇', name:'SVG to Component', brand:'react-svgr.com', desc:{zh:'矢量图标一键转为 React、Vue 或 Tailwind 组件代码',en:'Convert SVG icons to React / Vue / Tailwind components',ja:'SVGをReact/Vueコンポーネントに変換'}, href:'https://react-svgr.com/playground/', cat:'dev' },
    { icon:'🐳', name:'Docker Gen', brand:'composerize.com', desc:{zh:'通过可视化选项生成 Docker Compose 配置文件',en:'Generate Docker Compose configs visually',ja:'Docker Compose設定を自動生成'}, href:'https://www.composerize.com', cat:'dev' },
    { icon:'🪄', name:'Object Remover', brand:'objectremover.com', desc:{zh:'AI 智能擦除：涂抹即可无痕去除照片中的路人或杂物',en:'AI-powered object removal — just brush to erase',ja:'AIで写真の不要物を消去'}, href:'https://objectremover.com', cat:'image' },
    { icon:'💬', name:'Image to Prompt', brand:'imagetoprompt.com', desc:{zh:'上传 AI 图反推提示词（Prompt），还原创作思路',en:'Reverse-engineer AI image prompts from any picture',ja:'AI画像からプロンプトを逆算'}, href:'https://imagetoprompt.com', cat:'ai' },
    { icon:'🔍', name:'AI Upscaler', brand:'upscayl.org', desc:{zh:'AI 无损放大图片 4 倍，自动补全细节，开源免费',en:'Upscale images 4× with AI detail enhancement',ja:'AIで画像を4倍高解像度化'}, href:'https://www.upscayl.org', cat:'image' },
    { icon:'📄', name:'Chat with PDF', brand:'chatpdf.com', desc:{zh:'向长篇 PDF 直接提问，AI 自动总结重点和关键条款',en:'Ask any question to a PDF — AI summarizes key points',ja:'PDFに質問してAIが要約'}, href:'https://www.chatpdf.com', cat:'ai' },
    { icon:'✂️', name:'Remove.bg', brand:'remove.bg', desc:{zh:'发丝级精细扣图，一键去除背景，支持批量处理',en:'Remove image backgrounds at pixel-perfect quality',ja:'高精度な背景除去ツール'}, href:'https://www.remove.bg', cat:'image' },
    { icon:'📸', name:'Shots.so', brand:'shots.so', desc:{zh:'给普通截图套上 Mac / iPhone 外壳与高级背景',en:'Wrap screenshots in beautiful device mockups',ja:'スクリーンショットをデバイス枠で美化'}, href:'https://shots.so', cat:'design' },
    { icon:'🌊', name:'Haikei', brand:'haikei.app', desc:{zh:'随机生成丝滑 SVG 波浪、渐变形状，一键用于网页',en:'Generate smooth SVG waves and blobs for your site',ja:'SVGウェーブ・形状をランダム生成'}, href:'https://app.haikei.app', cat:'design' },
    { icon:'🌐', name:'OpenGraph.xyz', brand:'opengraph.xyz', desc:{zh:'输入网址预览分享到微信 / X 时的样式，排查 OG 问题',en:'Preview how your URL looks when shared on social media',ja:'SNSシェア時のプレビューを確認'}, href:'https://www.opengraph.xyz', cat:'seo' },
    { icon:'🎨', name:'Coolors', brand:'coolors.co', desc:{zh:'从照片提取配色或随机生成高级配色方案',en:'Extract palettes from photos or generate color schemes',ja:'写真から配色を抽出・生成'}, href:'https://coolors.co', cat:'design' },
    { icon:'🔄', name:'CloudConvert', brand:'cloudconvert.com', desc:{zh:'支持几乎所有格式的文件互转：PDF、视频、文档均可',en:'Convert almost any file format — PDF, video, docs',ja:'ほぼ全形式のファイル変換'}, href:'https://cloudconvert.com', cat:'convert' },
    { icon:'🔗', name:'Dub.co', brand:'dub.co', desc:{zh:'短链接 + 实时统计点击来源、地理位置和设备信息',en:'Short links with real-time click analytics',ja:'短縮URLとリアルタイム分析'}, href:'https://dub.co', cat:'seo' },
    { icon:'🚀', name:'PageSpeed', brand:'pagespeed.web.dev', desc:{zh:'一键诊断网站加载速度，提供具体优化建议',en:'Diagnose site speed and get actionable suggestions',ja:'サイト速度診断と改善提案'}, href:'https://pagespeed.web.dev', cat:'seo' },
    { icon:'🕷️', name:'Broken Link Check', brand:'brokenlinkcheck.com', desc:{zh:'全站扫描死链，找出所有 404 错误链接',en:'Scan your entire site for broken 404 links',ja:'サイト全体の壊れたリンクを検出'}, href:'https://www.brokenlinkcheck.com', cat:'seo' },
];

/* ── AI Tools ── */
const AI_TOOLS = [
    { cat:'write', icon:'✍️', name:'ChatGPT', tag:'OpenAI', href:'https://chat.openai.com' },
    { cat:'write', icon:'✨', name:'Claude', tag:'Anthropic', href:'https://claude.ai' },
    { cat:'write', icon:'🤖', name:'Gemini', tag:'Google', href:'https://gemini.google.com' },
    { cat:'write', icon:'📝', name:'Notion AI', tag:'Writing', href:'https://www.notion.so/product/ai' },
    { cat:'write', icon:'💼', name:'Copy.ai', tag:'Marketing', href:'https://www.copy.ai' },
    { cat:'write', icon:'📧', name:'Jasper', tag:'Content', href:'https://www.jasper.ai' },
    { cat:'image', icon:'🎨', name:'Midjourney', tag:'Image', href:'https://www.midjourney.com' },
    { cat:'image', icon:'🖼️', name:'DALL·E 3', tag:'OpenAI', href:'https://labs.openai.com' },
    { cat:'image', icon:'⚡', name:'Stable Diffusion', tag:'Image', href:'https://stability.ai' },
    { cat:'image', icon:'🎭', name:'Adobe Firefly', tag:'Adobe', href:'https://firefly.adobe.com' },
    { cat:'image', icon:'🌈', name:'Leonardo.ai', tag:'Image', href:'https://leonardo.ai' },
    { cat:'image', icon:'✂️', name:'Remove.bg', tag:'BG Remove', href:'https://www.remove.bg' },
    { cat:'video', icon:'🎬', name:'Sora', tag:'OpenAI', href:'https://sora.com' },
    { cat:'video', icon:'🎥', name:'Runway', tag:'Video', href:'https://runwayml.com' },
    { cat:'video', icon:'🎞️', name:'Pika', tag:'Video', href:'https://pika.art' },
    { cat:'video', icon:'📹', name:'HeyGen', tag:'Avatar', href:'https://www.heygen.com' },
    { cat:'video', icon:'🌊', name:'Kling AI', tag:'Video', href:'https://klingai.com' },
    { cat:'video', icon:'✂️', name:'CapCut AI', tag:'Edit', href:'https://www.capcut.com' },
    { cat:'code', icon:'💻', name:'GitHub Copilot', tag:'Code', href:'https://github.com/features/copilot' },
    { cat:'code', icon:'⚡', name:'Cursor', tag:'IDE', href:'https://cursor.sh' },
    { cat:'code', icon:'🔧', name:'Claude Code', tag:'Terminal', href:'https://claude.ai/code' },
    { cat:'code', icon:'🤖', name:'v0.dev', tag:'UI Gen', href:'https://v0.dev' },
    { cat:'code', icon:'🛠️', name:'Bolt.new', tag:'Fullstack', href:'https://bolt.new' },
    { cat:'code', icon:'🔍', name:'Tabnine', tag:'Code', href:'https://www.tabnine.com' },
    { cat:'chat', icon:'🔍', name:'Perplexity', tag:'Search', href:'https://www.perplexity.ai' },
    { cat:'chat', icon:'🌙', name:'DeepSeek', tag:'Chat', href:'https://chat.deepseek.com' },
    { cat:'chat', icon:'🦙', name:'Meta AI', tag:'Meta', href:'https://www.meta.ai' },
    { cat:'chat', icon:'🔥', name:'Grok', tag:'xAI', href:'https://grok.com' },
    { cat:'chat', icon:'🌐', name:'Kimi', tag:'月之暗面', href:'https://kimi.moonshot.cn' },
    { cat:'chat', icon:'🐋', name:'文心一言', tag:'百度', href:'https://yiyan.baidu.com' },
    { cat:'audio', icon:'🎵', name:'Suno', tag:'Music', href:'https://suno.ai' },
    { cat:'audio', icon:'🎤', name:'ElevenLabs', tag:'Voice', href:'https://elevenlabs.io' },
    { cat:'audio', icon:'🎙️', name:'Whisper', tag:'STT', href:'https://openai.com/research/whisper' },
    { cat:'audio', icon:'🔊', name:'Mubert', tag:'Music', href:'https://mubert.com' },
];

/* ── Tools (i18n) ── */
const TOOLS = {
    zh: [
        { title: '本站 · 本地', items: [
            { href: '/compress.html', icon: '🖼', title: 'PixCrush 图片压缩', tag: '本地', int: true },
        ]},
        { title: '文本与数据格式', items: [
            { href: 'https://regex101.com', icon: '.*', title: 'Regex101', tag: 'WEB' },
            { href: 'https://jsonformatter.org', icon: '{}', title: 'JSON 格式化', tag: 'WEB' },
            { href: 'https://www.diffchecker.com', icon: '⇄', title: '文本对比', tag: 'WEB' },
            { href: 'https://jsonformatter.org/yaml-to-json', icon: '▤', title: 'YAML / JSON', tag: 'WEB' },
            { href: 'https://dillinger.io', icon: 'M↓', title: 'Markdown 编辑', tag: 'WEB' },
            { href: 'https://csvjson.com/csv2json', icon: 'csv', title: 'CSV ↔ JSON', tag: 'WEB' },
            { href: 'https://www.uuidgenerator.net', icon: '#', title: 'UUID 生成', tag: 'WEB' },
            { href: 'https://www.epochconverter.com', icon: '⏲', title: 'Unix 时间戳', tag: 'WEB' },
            { href: 'https://gchq.github.io/CyberChef/', icon: '⌗', title: 'CyberChef 编解码', tag: 'WEB' },
            { href: 'https://prettier.io/playground/', icon: 'P', title: 'Prettier 在线格式化', tag: 'WEB' },
            { href: 'https://www.urlencoder.org/', icon: '%', title: 'URL 编解码', tag: 'WEB' },
            { href: 'https://csvjson.com/json2csv', icon: 'csv', title: 'JSON ↔ CSV', tag: 'WEB' },
        ]},
        { title: '前端、设计与可视化', items: [
            { href: 'https://caniuse.com', icon: '📊', title: 'Can I use', tag: 'WEB' },
            { href: 'https://excalidraw.com', icon: '✎', title: 'Excalidraw 白板', tag: 'WEB' },
            { href: 'https://svgomg.net', icon: '◇', title: 'SVG 压缩', tag: 'WEB' },
            { href: 'https://transform.tools', icon: '⇄', title: 'CSS / HTML 转换', tag: 'WEB' },
            { href: 'https://carbon.now.sh', icon: '❯', title: 'Carbon 代码图', tag: 'WEB' },
            { href: 'https://realfavicongenerator.net', icon: '★', title: 'Favicon 生成', tag: 'WEB' },
            { href: 'https://cssgradient.io', icon: '◐', title: 'CSS 渐变', tag: 'WEB' },
            { href: 'https://tailwindcss.com/docs/installation', icon: 'TW', title: 'Tailwind 文档', tag: 'WEB' },
            { href: 'https://cubic-bezier.com', icon: '∿', title: '贝塞尔曲线', tag: 'WEB' },
            { href: 'https://svg-path-visualizer.netlify.app/', icon: 'SVG', title: 'SVG Path 可视化', tag: 'WEB' },
            { href: 'https://fonts.google.com', icon: 'F', title: 'Google Fonts', tag: 'WEB' },
        ]},
        { title: '在线编码与沙盒', items: [
            { href: 'https://codesandbox.io', icon: '▣', title: 'CodeSandbox', tag: 'WEB' },
            { href: 'https://codepen.io', icon: 'cp', title: 'CodePen', tag: 'WEB' },
            { href: 'https://stackblitz.com', icon: '⚡', title: 'StackBlitz', tag: 'WEB' },
            { href: 'https://replit.com', icon: '›', title: 'Replit', tag: 'WEB' },
            { href: 'https://jsfiddle.net', icon: 'Fid', title: 'JSFiddle', tag: 'WEB' },
            { href: 'https://glitch.com', icon: 'G', title: 'Glitch', tag: 'WEB' },
        ]},
        { title: '运维、网络与调试', items: [
            { href: 'https://crontab.guru', icon: '⏱', title: 'Crontab 解释', tag: 'WEB' },
            { href: 'https://nginxconfig.io', icon: 'N', title: 'Nginx 配置', tag: 'WEB' },
            { href: 'https://explainshell.com', icon: '$', title: 'Explain Shell', tag: 'WEB' },
            { href: 'https://httpbin.org', icon: 'http', title: 'httpbin 请求测试', tag: 'WEB' },
            { href: 'https://dnschecker.org', icon: '@', title: 'DNS 传播检测', tag: 'WEB' },
            { href: 'https://www.whatsmydns.net', icon: 'DNS', title: 'DNS 查询', tag: 'WEB' },
            { href: 'https://webhook.site', icon: '→', title: 'Webhook 调试', tag: 'WEB' },
            { href: 'https://www.ssllabs.com/ssltest/', icon: 'TLS', title: 'SSL 服务器测试', tag: 'WEB' },
            { href: 'https://fast.com', icon: '⚡', title: '网速测试', tag: 'WEB' },
        ]},
        { title: '数据库、安全与文档', items: [
            { href: 'https://sqliteviewer.app', icon: '🗂', title: 'SQLite 查看', tag: 'WEB' },
            { href: 'https://www.db-fiddle.com', icon: 'SQL', title: 'DB Fiddle', tag: 'WEB' },
            { href: 'https://jwt.io', icon: '🔑', title: 'JWT 调试', tag: 'WEB' },
            { href: 'https://base64.guru/converter/encode/image', icon: '64', title: '图片 Base64', tag: 'WEB' },
            { href: 'https://readme.so', icon: '📝', title: 'README 编辑器', tag: 'WEB' },
            { href: 'https://shields.io', icon: '▬', title: 'Shields 徽章', tag: 'WEB' },
            { href: 'https://editor.swagger.io/', icon: 'OAS', title: 'OpenAPI 编辑器', tag: 'WEB' },
            { href: 'https://mermaid.live', icon: 'M', title: 'Mermaid 图表', tag: 'WEB' },
        ]},
    ],
    en: [
        { title: 'On-site · local', items: [
            { href: '/compress.html', icon: '🖼', title: 'PixCrush images', tag: 'Local', int: true },
        ]},
        { title: 'Text & data formats', items: [
            { href: 'https://regex101.com', icon: '.*', title: 'Regex101', tag: 'WEB' },
            { href: 'https://jsonformatter.org', icon: '{}', title: 'JSON formatter', tag: 'WEB' },
            { href: 'https://www.diffchecker.com', icon: '⇄', title: 'Diff checker', tag: 'WEB' },
            { href: 'https://jsonformatter.org/yaml-to-json', icon: '▤', title: 'YAML / JSON', tag: 'WEB' },
            { href: 'https://dillinger.io', icon: 'M↓', title: 'Markdown', tag: 'WEB' },
            { href: 'https://csvjson.com/csv2json', icon: 'csv', title: 'CSV ↔ JSON', tag: 'WEB' },
            { href: 'https://www.uuidgenerator.net', icon: '#', title: 'UUID', tag: 'WEB' },
            { href: 'https://www.epochconverter.com', icon: '⏲', title: 'Unix timestamp', tag: 'WEB' },
            { href: 'https://gchq.github.io/CyberChef/', icon: '⌗', title: 'CyberChef', tag: 'WEB' },
            { href: 'https://prettier.io/playground/', icon: 'P', title: 'Prettier playground', tag: 'WEB' },
            { href: 'https://www.urlencoder.org/', icon: '%', title: 'URL encoder/decoder', tag: 'WEB' },
            { href: 'https://csvjson.com/json2csv', icon: 'csv', title: 'JSON ↔ CSV', tag: 'WEB' },
        ]},
        { title: 'Front-end, design & UI', items: [
            { href: 'https://caniuse.com', icon: '📊', title: 'Can I use', tag: 'WEB' },
            { href: 'https://excalidraw.com', icon: '✎', title: 'Excalidraw', tag: 'WEB' },
            { href: 'https://svgomg.net', icon: '◇', title: 'SVGOMG', tag: 'WEB' },
            { href: 'https://transform.tools', icon: '⇄', title: 'CSS / HTML tools', tag: 'WEB' },
            { href: 'https://carbon.now.sh', icon: '❯', title: 'Carbon screenshots', tag: 'WEB' },
            { href: 'https://realfavicongenerator.net', icon: '★', title: 'Favicon generator', tag: 'WEB' },
            { href: 'https://cssgradient.io', icon: '◐', title: 'CSS gradients', tag: 'WEB' },
            { href: 'https://tailwindcss.com/docs/installation', icon: 'TW', title: 'Tailwind docs', tag: 'WEB' },
            { href: 'https://cubic-bezier.com', icon: '∿', title: 'Cubic-bezier', tag: 'WEB' },
            { href: 'https://svg-path-visualizer.netlify.app/', icon: 'SVG', title: 'SVG path visualizer', tag: 'WEB' },
            { href: 'https://fonts.google.com', icon: 'F', title: 'Google Fonts', tag: 'WEB' },
        ]},
        { title: 'Online IDEs & sandboxes', items: [
            { href: 'https://codesandbox.io', icon: '▣', title: 'CodeSandbox', tag: 'WEB' },
            { href: 'https://codepen.io', icon: 'cp', title: 'CodePen', tag: 'WEB' },
            { href: 'https://stackblitz.com', icon: '⚡', title: 'StackBlitz', tag: 'WEB' },
            { href: 'https://replit.com', icon: '›', title: 'Replit', tag: 'WEB' },
            { href: 'https://jsfiddle.net', icon: 'Fid', title: 'JSFiddle', tag: 'WEB' },
            { href: 'https://glitch.com', icon: 'G', title: 'Glitch', tag: 'WEB' },
        ]},
        { title: 'DevOps, network & debug', items: [
            { href: 'https://crontab.guru', icon: '⏱', title: 'Crontab guru', tag: 'WEB' },
            { href: 'https://nginxconfig.io', icon: 'N', title: 'nginx config', tag: 'WEB' },
            { href: 'https://explainshell.com', icon: '$', title: 'Explain shell', tag: 'WEB' },
            { href: 'https://httpbin.org', icon: 'http', title: 'httpbin', tag: 'WEB' },
            { href: 'https://dnschecker.org', icon: '@', title: 'DNS propagation', tag: 'WEB' },
            { href: 'https://www.whatsmydns.net', icon: 'DNS', title: 'DNS lookup', tag: 'WEB' },
            { href: 'https://webhook.site', icon: '→', title: 'Webhook tester', tag: 'WEB' },
            { href: 'https://www.ssllabs.com/ssltest/', icon: 'TLS', title: 'SSL server test', tag: 'WEB' },
            { href: 'https://fast.com', icon: '⚡', title: 'Speed test', tag: 'WEB' },
        ]},
        { title: 'DB, security & docs', items: [
            { href: 'https://sqliteviewer.app', icon: '🗂', title: 'SQLite viewer', tag: 'WEB' },
            { href: 'https://www.db-fiddle.com', icon: 'SQL', title: 'DB Fiddle', tag: 'WEB' },
            { href: 'https://jwt.io', icon: '🔑', title: 'JWT.io', tag: 'WEB' },
            { href: 'https://base64.guru/converter/encode/image', icon: '64', title: 'Image → Base64', tag: 'WEB' },
            { href: 'https://readme.so', icon: '📝', title: 'readme.so', tag: 'WEB' },
            { href: 'https://shields.io', icon: '▬', title: 'Shields.io badges', tag: 'WEB' },
            { href: 'https://editor.swagger.io/', icon: 'OAS', title: 'OpenAPI editor', tag: 'WEB' },
            { href: 'https://mermaid.live', icon: 'M', title: 'Mermaid live', tag: 'WEB' },
        ]},
    ],
    ja: [
        { title: '当サイト · ローカル', items: [
            { href: '/compress.html', icon: '🖼', title: 'PixCrush 画像', tag: 'ローカル', int: true },
        ]},
        { title: 'テキスト・データ形式', items: [
            { href: 'https://regex101.com', icon: '.*', title: 'Regex101', tag: 'WEB' },
            { href: 'https://jsonformatter.org', icon: '{}', title: 'JSON', tag: 'WEB' },
            { href: 'https://www.diffchecker.com', icon: '⇄', title: 'Diff', tag: 'WEB' },
            { href: 'https://jsonformatter.org/yaml-to-json', icon: '▤', title: 'YAML / JSON', tag: 'WEB' },
            { href: 'https://dillinger.io', icon: 'M↓', title: 'Markdown', tag: 'WEB' },
            { href: 'https://csvjson.com/csv2json', icon: 'csv', title: 'CSV ↔ JSON', tag: 'WEB' },
            { href: 'https://www.uuidgenerator.net', icon: '#', title: 'UUID', tag: 'WEB' },
            { href: 'https://www.epochconverter.com', icon: '⏲', title: 'UNIX 時刻', tag: 'WEB' },
            { href: 'https://gchq.github.io/CyberChef/', icon: '⌗', title: 'CyberChef', tag: 'WEB' },
            { href: 'https://prettier.io/playground/', icon: 'P', title: 'Prettier', tag: 'WEB' },
            { href: 'https://www.urlencoder.org/', icon: '%', title: 'URL エンコード', tag: 'WEB' },
            { href: 'https://csvjson.com/json2csv', icon: 'csv', title: 'JSON ↔ CSV', tag: 'WEB' },
        ]},
        { title: 'フロント・デザイン', items: [
            { href: 'https://caniuse.com', icon: '📊', title: 'Can I use', tag: 'WEB' },
            { href: 'https://excalidraw.com', icon: '✎', title: 'Excalidraw', tag: 'WEB' },
            { href: 'https://svgomg.net', icon: '◇', title: 'SVGOMG', tag: 'WEB' },
            { href: 'https://transform.tools', icon: '⇄', title: 'CSS / HTML', tag: 'WEB' },
            { href: 'https://carbon.now.sh', icon: '❯', title: 'Carbon', tag: 'WEB' },
            { href: 'https://realfavicongenerator.net', icon: '★', title: 'Favicon', tag: 'WEB' },
            { href: 'https://cssgradient.io', icon: '◐', title: 'CSS グラデ', tag: 'WEB' },
            { href: 'https://tailwindcss.com/docs/installation', icon: 'TW', title: 'Tailwind', tag: 'WEB' },
            { href: 'https://cubic-bezier.com', icon: '∿', title: 'ベジェ曲線', tag: 'WEB' },
            { href: 'https://svg-path-visualizer.netlify.app/', icon: 'SVG', title: 'SVG パス', tag: 'WEB' },
            { href: 'https://fonts.google.com', icon: 'F', title: 'Google Fonts', tag: 'WEB' },
        ]},
        { title: 'IDE・サンドボックス', items: [
            { href: 'https://codesandbox.io', icon: '▣', title: 'CodeSandbox', tag: 'WEB' },
            { href: 'https://codepen.io', icon: 'cp', title: 'CodePen', tag: 'WEB' },
            { href: 'https://stackblitz.com', icon: '⚡', title: 'StackBlitz', tag: 'WEB' },
            { href: 'https://replit.com', icon: '›', title: 'Replit', tag: 'WEB' },
            { href: 'https://jsfiddle.net', icon: 'Fid', title: 'JSFiddle', tag: 'WEB' },
            { href: 'https://glitch.com', icon: 'G', title: 'Glitch', tag: 'WEB' },
        ]},
        { title: '運用・ネットワーク', items: [
            { href: 'https://crontab.guru', icon: '⏱', title: 'Crontab', tag: 'WEB' },
            { href: 'https://nginxconfig.io', icon: 'N', title: 'nginx', tag: 'WEB' },
            { href: 'https://explainshell.com', icon: '$', title: 'Explain shell', tag: 'WEB' },
            { href: 'https://httpbin.org', icon: 'http', title: 'httpbin', tag: 'WEB' },
            { href: 'https://dnschecker.org', icon: '@', title: 'DNS 確認', tag: 'WEB' },
            { href: 'https://www.whatsmydns.net', icon: 'DNS', title: 'DNS ルックアップ', tag: 'WEB' },
            { href: 'https://webhook.site', icon: '→', title: 'Webhook', tag: 'WEB' },
            { href: 'https://www.ssllabs.com/ssltest/', icon: 'TLS', title: 'SSL テスト', tag: 'WEB' },
            { href: 'https://fast.com', icon: '⚡', title: 'スピードテスト', tag: 'WEB' },
        ]},
        { title: 'DB・セキュリティ・文書', items: [
            { href: 'https://sqliteviewer.app', icon: '🗂', title: 'SQLite', tag: 'WEB' },
            { href: 'https://www.db-fiddle.com', icon: 'SQL', title: 'DB Fiddle', tag: 'WEB' },
            { href: 'https://jwt.io', icon: '🔑', title: 'JWT', tag: 'WEB' },
            { href: 'https://base64.guru/converter/encode/image', icon: '64', title: 'Base64 画像', tag: 'WEB' },
            { href: 'https://readme.so', icon: '📝', title: 'readme.so', tag: 'WEB' },
            { href: 'https://shields.io', icon: '▬', title: 'Shields', tag: 'WEB' },
            { href: 'https://editor.swagger.io/', icon: 'OAS', title: 'OpenAPI', tag: 'WEB' },
            { href: 'https://mermaid.live', icon: 'M', title: 'Mermaid', tag: 'WEB' },
        ]},
    ],
};

const TOOL_CAT_MAP = {
    text:     ['本站 · 本地','文本与数据格式','Text & data formats','テキスト・データ形式','On-site · local'],
    frontend: ['前端、设计与可视化','Front-end, design & UI','フロント・デザイン'],
    sandbox:  ['在线编码与沙盒','Online IDEs & sandboxes','IDE・サンドボックス'],
    devops:   ['运维、网络与调试','DevOps, network & debug','運用・ネットワーク'],
    db:       ['数据库、安全与文档','DB, security & docs','DB・セキュリティ・文書'],
};

/* ── Fallback Data ── */
const OSS_FALLBACK = [
    { html_url:'https://github.com/facebook/react', full_name:'facebook/react', description:{zh:'构建交互式界面的主流前端库。',en:'A mainstream library for building interactive user interfaces.',ja:'対話的な UI を構築する代表的なフロントエンドライブラリ。'}, language:'JavaScript', stargazers_count:235000, owner:{avatar_url:'https://avatars.githubusercontent.com/u/69631?v=4'} },
    { html_url:'https://github.com/vuejs/core', full_name:'vuejs/core', description:{zh:'易上手、生态成熟的渐进式前端框架核心仓库。',en:'The core repository of a progressive framework with a mature ecosystem.',ja:'学びやすく成熟したエコシステムを持つプログレッシブフレームワークの中核。'}, language:'TypeScript', stargazers_count:49000, owner:{avatar_url:'https://avatars.githubusercontent.com/u/6128107?v=4'} },
    { html_url:'https://github.com/tailwindlabs/tailwindcss', full_name:'tailwindlabs/tailwindcss', description:{zh:'高效搭建界面的原子化 CSS 框架。',en:'A utility-first CSS framework for building interfaces quickly.',ja:'素早く UI を組み立てられるユーティリティファースト CSS フレームワーク。'}, language:'TypeScript', stargazers_count:84000, owner:{avatar_url:'https://avatars.githubusercontent.com/u/67109815?v=4'} },
    { html_url:'https://github.com/vercel/next.js', full_name:'vercel/next.js', description:{zh:'用于生产环境的 React 全栈框架。',en:'A production-grade full-stack framework built on React.',ja:'React ベースの本番向けフルスタックフレームワーク。'}, language:'JavaScript', stargazers_count:131000, owner:{avatar_url:'https://avatars.githubusercontent.com/u/14985020?v=4'} },
    { html_url:'https://github.com/denoland/deno', full_name:'denoland/deno', description:{zh:'现代 JavaScript 与 TypeScript 运行时。',en:'A modern runtime for JavaScript and TypeScript.',ja:'モダンな JavaScript / TypeScript ランタイム。'}, language:'Rust', stargazers_count:98000, owner:{avatar_url:'https://avatars.githubusercontent.com/u/42048915?v=4'} },
    { html_url:'https://github.com/shadcn-ui/ui', full_name:'shadcn-ui/ui', description:{zh:'面向产品界面的可组合组件集合。',en:'Composable UI components oriented toward product interfaces.',ja:'プロダクト UI 向けの組み合わせ可能なコンポーネント集。'}, language:'TypeScript', stargazers_count:83000, owner:{avatar_url:'https://avatars.githubusercontent.com/u/139895814?v=4'} },
];

const SOFT_FALLBACK = [
    { html_url:'https://github.com/sharkdp/bat', name:'bat', description:{zh:'带语法高亮和 Git diff 的现代 cat 替代工具。',en:'A modern cat replacement with syntax highlighting and Git integration.',ja:'シンタックスハイライトと Git 連携を備えた modern cat 代替。'}, language:'Rust', owner:{avatar_url:'https://avatars.githubusercontent.com/u/277052?v=4'} },
    { html_url:'https://github.com/ogham/exa', name:'exa', description:{zh:'更现代的 ls 替代品，适合命令行可视化浏览。',en:'A modern replacement for ls with a friendlier terminal view.',ja:'ターミナルで見やすい ls 代替ツール。'}, language:'Rust', owner:{avatar_url:'https://avatars.githubusercontent.com/u/175525?v=4'} },
    { html_url:'https://github.com/sharkdp/fd', name:'fd', description:{zh:'比 find 更快更友好的文件查找工具。',en:'A simpler and faster alternative to find.',ja:'find よりシンプルで高速なファイル検索ツール。'}, language:'Rust', owner:{avatar_url:'https://avatars.githubusercontent.com/u/277052?v=4'} },
    { html_url:'https://github.com/BurntSushi/ripgrep', name:'ripgrep', description:{zh:'面向代码库搜索的高性能文本搜索工具。',en:'A high-performance text search tool ideal for codebases.',ja:'コードベース検索に強い高速テキスト検索ツール。'}, language:'Rust', owner:{avatar_url:'https://avatars.githubusercontent.com/u/456674?v=4'} },
    { html_url:'https://github.com/junegunn/fzf', name:'fzf', description:{zh:'命令行模糊搜索神器，适合文件、历史和命令导航。',en:'A fuzzy finder for files, history, and command navigation.',ja:'ファイル・履歴・コマンド移動に便利な fuzzy finder。'}, language:'Go', owner:{avatar_url:'https://avatars.githubusercontent.com/u/700826?v=4'} },
    { html_url:'https://github.com/ajeetdsouza/zoxide', name:'zoxide', description:{zh:'更聪明的 cd，按使用频率快速跳目录。',en:'A smarter cd that jumps to directories based on frequency.',ja:'使用頻度から素早く移動できる賢い cd 代替。'}, language:'Rust', owner:{avatar_url:'https://avatars.githubusercontent.com/u/5403999?v=4'} },
];
